version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: battery_repair
      POSTGRES_USER: battery_user
      POSTGRES_PASSWORD: battery_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://battery_user:battery_password@postgres:5432/battery_repair
      SESSION_SECRET: your-secret-key-change-this-in-production
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./instance:/app/instance

volumes:
  postgres_data: